config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from heimdall.users.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("heimdall.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("athena/", include("heimdall.athena.urls")),

    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

heimdall/athena/urls.py
from django.urls import path
from heimdall.athena import views


urlpatterns = [
    path("", views.home_view, name="athena-home"),
    path("data/<int:pk>/", views.data_detail, name="data-detail"),
    path("new-rate/", views.predict_view, name="new-rate"),

]

heimdall/users/urls.py
from django.urls import path

from heimdall.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    product_view,
    new_product_view,
    new_keyword_view,
    edit_keyword_view
)
from heimdall.users import views

app_name = "users"
urlpatterns = [
    path("new-product/", view=new_product_view, name="new-product"),
    path("new-keywords/", view=new_keyword_view, name="new-keywords"),
    path("edit-keywords/<int:pk>/", view=edit_keyword_view, name="edit-keywords"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("products/<str:slug>/", view=product_view, name="product-detail"),

]

heimdall/athena/models.py
from django.db import models
from heimdall.users.models import Product
from django.core.validators import MaxValueValidator

from heimdall.athena.utils import get_raw_data, get_text_data, get_title

import numpy as np
from heimdall.users.ml_utils import get_new_rate


class BaseModel(models.Model):
    is_removed = models.BooleanField(default=False)

    class Meta:
        abstract = True
        app_label = 'athena'


class ScrapedData(BaseModel):
    """Model to store web scraped data"""
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    title = models.CharField(max_length=255)
    source = models.CharField(max_length=300)
    raw_data = models.TextField()
    text_data = models.TextField()
    generated_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.title = get_title(self.source)
        self.raw_data = get_raw_data(self.source)
        self.text_data = get_text_data(self.source)
        super(ScrapedData, self).save(*args, **kwargs)


class ProductInsight(BaseModel):

    MONTH = [
        ('January', 'January'),
        ('February', 'February'),
        ('March', 'March'),
        ('April', 'April'),
        ('May', 'May'),
        ('June', 'June'),
        ('July', 'July'),
        ('August', 'August'),
        ('September', 'September'),
        ('October', 'October'),
        ('November', 'November'),
        ('December', 'December'),
    ]

    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    production_capacity = models.PositiveBigIntegerField()
    month = models.CharField(max_length=15, choices=MONTH)
    year = models.PositiveBigIntegerField(validators=[MaxValueValidator(2100)])
    sales = models.PositiveBigIntegerField()

    def __str__(self):
        return self.product.name + " | " + str(self.month) + " - " + str(self.year)


class AttributeHitScore(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    hit_rate = models.FloatField()
    generated_on = models.DateTimeField(auto_now_add=True)


class NewRate(ProductInsight):
    produced = models.PositiveIntegerField()
    hit_rate = models.FloatField()
    new_rate = models.FloatField(null=True, blank=True)
    generated_on = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        attrs = np.array(
            [[
                float(self.production_capacity),
                float(self.produced),
                float(self.sales),
                float(self.hit_rate),
            ]]
        )

        self.new_rate = get_new_rate(attrs)
        super(NewRate, self).save(*args, **kwargs)

heimdall/athena/forms.py
from django import forms
from heimdall.athena.models import ScrapedData, NewRate
from heimdall.users.models import Product


class NewDataForm(forms.ModelForm):
    class Meta:
        model = ScrapedData
        fields = ('product', 'source')

    def __init__(self, *args, **kwargs):
        cmp_id = kwargs.pop('cmp_id')
        super(NewDataForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.filter(company_id=cmp_id)


class NewRateForm(forms.ModelForm):
    class Meta:
        model = NewRate
        fields = ('product', 'production_capacity', 'produced', 'month', 'year', 'sales', 'hit_rate')

    def __init__(self, *args, **kwargs):
        cmp_id = kwargs.pop('cmp_id')
        super(NewRateForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.filter(company_id=cmp_id)

heimdall/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms
from heimdall.users.models import Product, Company, ProductKeyword

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class NewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('company', 'name', 'description', 'product_site_url', 'keywords')

    def __init__(self, *args, **kwargs):
        cmp_id = kwargs.pop('cmp_id')
        super(NewProductForm, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.filter(id=cmp_id)


class NewProductKeywordForm(forms.ModelForm):
    class Meta:
        model = ProductKeyword
        fields = ('product', 'company', 'keywords')

    def __init__(self, *args, **kwargs):
        cmp_id = kwargs.pop('cmp_id')
        super(NewProductKeywordForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.filter(company_id=cmp_id)
        self.fields['company'].queryset = Company.objects.filter(id=cmp_id)


class EditKeywordsForm(forms.ModelForm):
    class Meta:
        model = ProductKeyword
        fields = ('keywords',)
    
    def __init__(self, *args, **kwargs):
        super(EditKeywordsForm, self).__init__(*args, **kwargs)
        product_keywords = kwargs.pop('instance')
        self.fields['keywords'].queryset = ProductKeyword.objects.get(id=product_keywords.id)
    

heimdall/athena/views.py
import os
from django.shortcuts import render, redirect
from django.conf import settings

from heimdall.athena.forms import NewDataForm, NewRateForm
from heimdall.athena.utils import get_raw_data
from heimdall.athena.models import ScrapedData, NewRate
from heimdall.users.ml_utils import get_new_rate

import numpy as np


def home_view(request):
    if request.method == "POST":
        new_data_form = NewDataForm(request.POST, cmp_id=request.user.company_id)
        if new_data_form.is_valid():

            new_data_form.save()
            return redirect('/')
    new_data_form = NewDataForm(cmp_id=request.user.company_id)
    scraped_datas = ScrapedData.objects.all()
    context = {
        'new_data_form': new_data_form,
        'scraped_datas': scraped_datas,
    }
    return render(request, 'athena/home.html', context)


def data_detail(request, pk):
    data_instance = ScrapedData.objects.get(id=pk)
    context = {
        'data_instance': data_instance
    }
    return render(request, 'athena/data_detail.html', context)


def predict_view(request):
    if request.method == "POST":
        new_rate_form = NewRateForm(request.POST, cmp_id=request.user.company_id)
        if new_rate_form.is_valid():
            new_rate_form.save()
            return redirect('/')

    new_rate_form = NewRateForm(cmp_id=request.user.company_id)
    prod_rates = NewRate.objects.all().order_by('-generated_on')
    context = {
        "new_rate_form": new_rate_form,
        'prod_rates': prod_rates,
    }

    return render(request, 'athena/new_rate_form.html', context)

heimdall/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

heimdall/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django.shortcuts import redirect, render
# from django.http.response import Http404

from heimdall.users.models import User, Company, Product, ProductKeyword  # noqa
from heimdall.users.forms import NewProductForm, NewProductKeywordForm, EditKeywordsForm

class AdminMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.is_superuser or user.is_company_admin


class UserDetailView(LoginRequiredMixin, generic.DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, generic.RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class HomeView(LoginRequiredMixin, generic.ListView):
    model = Product
    template_name = 'users/home.html'

    def get_queryset(self):
        current_user = self.request.user
        queryset = Product.objects.filter(company_id=current_user.company_id)
        return queryset


class ProductView(LoginRequiredMixin, generic.DetailView):
    model = Product
    template_name = 'users/product_detail.html'
    slug_field = "slug"

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        keywords = ProductKeyword.objects.get(product_id=self.object.id)
        context['keyword'] = keywords.keywords.split('\n')
        context['keywords'] = ProductKeyword.objects.get(product_id=self.object.id)
        return context


product_view = ProductView.as_view()


def new_product_view(request):
    if request.method == 'POST':
        new_product_form = NewProductForm(request.POST, cmp_id=request.user.company_id)
        new_keyword_form = NewProductKeywordForm(request.POST, cmp_id=request.user.company_id)
        if new_product_form.is_valid():
            new_product_form.save()
            return redirect('new-keywords/')
    new_product_form = NewProductForm(cmp_id=request.user.company_id)
    new_keyword_form = NewProductKeywordForm(cmp_id=request.user.company_id)
    context = {
        "new_product_form": new_product_form,
        "new_keyword_form": new_keyword_form,
    }
    return render(request, 'users/new_product.html', context)


def new_keyword_view(request):
    if request.method == 'POST':
        new_keyword_form = NewProductKeywordForm(request.POST, cmp_id=request.user.company_id)
        if new_keyword_form.is_valid():
            new_keyword_form.save()
            return redirect('/')
    new_keyword_form = NewProductKeywordForm(cmp_id=request.user.company_id)
    context = {
        "new_keyword_form": new_keyword_form,
    }
    return render(request, 'users/new_keyword.html', context)


def edit_keyword_view(request, pk):
    product_keyword = ProductKeyword.objects.get(id=pk)

    if request.method == 'POST':
        keyword_form = EditKeywordsForm(request.POST,  instance=product_keyword)
        if keyword_form.is_valid():
            keyword_form.save()
            return redirect('/')
    keyword_form = EditKeywordsForm(instance=product_keyword)
    context = {
        'keyword_form': keyword_form
        }

    return render(request, 'users/edit_keywords.html', context)

heimdall/templates/users/edit_keywords.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<h1>edit keywords</h1>

Product: {{keywords.product}}

<form action="" method="POST">
    {% csrf_token %}
    {{keyword_form.as_p}}
    <button class="btn btn-success">&nbsp; Update &nbsp; </button>        
</form>

{% endblock %}

heimdall/templates/users/home.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="main">
    <div class="row">
        <div class="col-9 product-col">
          <div class="title-product">
          <a href="{% url 'users:new-product' %}" target="_blank" class="btn btn-success new-prod-button">New Product</a>
          <p>Products</p>
          </div>
        {% for product in object_list %}
          <div class="card home-cards">
            <img src="{% static 'images/heimdall.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">
              <a href="{% url 'users:product-detail' product.slug %}" class="anchor-product">{{product.name}}</a> 
              </h5>
              <p class="card-text">{{product.description | truncatechars:100}}</p>
            </div>
          </div>
		  
      {% endfor %}
	</div>

	  <div class="col-3">
        <div class="card home-cards">
            <img src="{% static 'images/heimdall.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">
                <a href="#" class="anchor-inventory">Inventory</a>
              </h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
        </div>
      </div>
    </div>
</div>

{% endblock content %}

heimdall/templates/users/new_keyword.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<h1>keywords</h1>

<form action="" method="post">
    {% csrf_token %}
    {{new_keyword_form.as_p}}
    <br>
    <button class="btn btn-success">Submit</button>
</form>


{% endblock %}

heimdall/templates/users/new_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>new product</h1>

{% endblock %}

heimdall/templates/users/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{product.name}} | {{product.company}} {% endblock title %}

{% block content %}

<h1>{{product.name}}</h1>
<h3>{{product.company}}</h3>

<p></p>



<div class="card" style="width: 250px; height: 200px; display: table; ">
    <div style="padding-left: 10px; display: table-cell; vertical-align: middle;">
      <h4>Keywords:</h4>
      {% for keyword in keyword  %}
          {{keyword}} <br>
      {% endfor %}
      <!-- <div> -->
        <a href="{% url 'users:edit-keywords' keywords.pk %}" class="btn btn-sm btn-primary">Add Keywords</a>

      <!-- </div> -->
    </div>
 </div>
  


<div class="card" style="width: 1000px; height: 200px; display: table; margin-top: 10px;">
    <div style="padding-left: 10px; padding-right: 10px; padding-top: 10px; display: table-cell;">
        {{product.description}} 
        <div style=" display: flex; align-items: center; justify-content: right;">
            <a style="width: 75px;" href="#" class="btn btn-sm btn-primary">Edit</a>
        </div>
    </div>
    
</div>
  

{% endblock content %}

heimdall/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

heimdall/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}